const guests = {
    FETCH_GUESTS_PENDING: 'FETCH_GUESTS_PENDING',
    FETCH_GUESTS_SUCCESS: 'FETCH_GUESTS_SUCCESS',
    FETCH_GUESTS_ERROR: 'FETCH_GUESTS_ERROR'
};

const hosts = {
    FETCH_HOSTS_PENDING: 'FETCH_HOSTS_PENDING',
    FETCH_HOSTS_SUCCESS: 'FETCH_HOSTS_SUCCESS',
    FETCH_HOSTS_ERROR: 'FETCH_HOSTS_ERROR'
};

const match = {
    MATCH_PENDING: 'MATCH_PENDING',
    MATCH_SUCCESS: 'MATCH_SUCCESS',
    MATCH_ERROR: 'MATCH_ERROR'
};

const ui = {
    SET_REGION: 'SET_REGION',
    SELECT_GUEST: 'SELECT_GUEST',
    SELECT_HOST: 'SELECT_HOST'
};

export { guests, hosts, ui, match };

