module.exports = {
    'Mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk': 'People that speaks norwegian invites someone who wants to learn norwegian for a dinner',
    'Hvis du vil komme på middag, eller invitere noen på middag registrerer du deg nedenfor. Vi matcher dere basert på hvem dere er og hvor dere bor og setter dere i kontakt for å avtale tidspunkt.': 'If you want to join a dinner or invite someone for a dinner register below. We will match you based on who you are and where you live. We will then set you in touch with each other',
    'Du finner mer informasjon på': 'More information are available here',

    'Hva vil du': 'What do you to do',
    'Komme til noen på middagsbesøk': 'Join someone for dinner',
    'Invitere noen på middagsbesøk': 'Invite someone to dinner',
    'Hva er navnet ditt': 'What\'s your name',
    'Hva er e-postadressen din': 'What\'s your email address',
    'Hva er telefonnummeret ditt': 'What\'s your phone number',
    'Er det noe mat du ikke spiser': 'Is there any food you don\'t eat',
    'Er du': 'Are you',
    'Kjønn': 'Gender',
    'Mann': 'Man',
    'Kvinne': 'Woman',
    'Menn': 'Men',
    'Kvinner': 'Females',
    'Barn': 'Children',
    'Alder': 'Age',
    'År': 'Years',
    'Antall barn': 'Children',
    'Antall voksne menn': 'Male adults',
    'Antall voksne kvinner': 'Female adults',
    'Hvor er du fra': 'Where are you from',
    'Hvor mange blir med på middag': 'How many people are you bringing',
    'Er det noe mat du/dere ikke spiser': 'Are there any food you don\'t eat',
    'Adresse': 'Address',
    'Postnummer': 'Zip code',
    'Kan du fortelle litt mer om deg selv': 'Can you tell us a bit more about yourself',
    'Er det noe annet vi trenger å vite om deg/dere': 'Is there anything else we should know about you',
    'Send inn': 'Submit',
}