module.exports = {
    'Mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk': 'People that speak Norwegian invite people who want to learn Norwegian over for dinner',
    'Hvis du vil komme på middag, eller invitere noen på middag registrerer du deg nedenfor. Vi matcher dere basert på hvem dere er og hvor dere bor og setter dere i kontakt for å avtale tidspunkt.': 'If you want to join a dinner or invite someone for a dinner register below. We will match you based on who you are and where you live. We will then set you in touch with each other',
    'Du finner mer informasjon på': 'More information are available here',
    'Takk for at du har meldt deg på!': 'Thank you for signing up!',
    'Hva vil du': 'What do you to do',
    'Komme til noen på middagsbesøk': 'Join someone for dinner',
    'Invitere noen på middagsbesøk': 'Invite someone to dinner',
    'Hva er navnet ditt': 'What\'s your name',
    'Hva er e-postadressen din': 'What\'s your email address',
    'Hva er telefonnummeret ditt': 'What\'s your phone number',
    'Er det noe mat du ikke spiser': 'Is there any food you don\'t eat',
    'Er du': 'Are you',
    'Kjønn': 'Gender',
    'Mann': 'Male',
    'Kvinne': 'Female',
    'Menn': 'Men',
    'Kvinner': 'Women',
    'Barn': 'Children',
    'Alder': 'Age',
    'Fyll inn': 'Enter',
    'Fyll inn et tall': 'Enter a number',
    'År': 'Years',
    'Antall barn': 'Children',
    'Antall voksne menn': 'Male adults',
    'Antall voksne kvinner': 'Female adults',
    'Hvor er du fra': 'Where are you from',
    'Hvor mange blir med på middag': 'How many is coming to dinner',
    'Er det noe mat du/dere ikke spiser': 'Is there any food you don\'t eat',
    'Adresse': 'Address',
    'Dette er ikke et gyldig navn':'This is not a valid name',
    'Dette er ikke en gyldig alder':'This is not a valid age',
    'Dette er ikke et gyldig sted':'This is not a valid location',
    'Dette er ikke et gyldig nummer':'This is not a valid number',
    'Dette er ikke en gyldig epost':'This is not a valid email',
    'Dette er ikke et gyldig telefonnummer':'This is not a valid phone number',
    'Dette er ikke en gyldig adresse':'This is not a valid address',
    'Dette er ikke en gyldig postnummer':'This is not a valid zipcode',
    'Postnummer': 'Zip code',
    'Hvem er du': "Who are you",
    'Vil du heller invitere noen på middag,': 'Would you rather invite someone,',
    'gå til skjema for vert.': 'go to the form for hosts.',
    'Vil du heller bli invitert på middag,': 'Would you rather be invited,',
    'gå til skjema for gjest.': 'go to the form for guests.',
    'Jeg vil komme på middag!': 'I would like to be invited to a dinner!',
    'Jeg vil invitere noen på middag!': 'I would like to invite someone over for dinner!',
    'Vil du øve på å snakke norsk? Ideen bak Kom inn er at mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk.':
        'Do you wish to practise speaking Norwegian? The concept behind Kom inn is to match people that speak norwegian with those who wish to practice and do so over dinner.',
    'Vil du hjelpe noen å lære norsk? Ideen bak Kom inn er at mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk.':
        'Do you wish to help someone learn Norwegian? The concept behind Kom inn is to match people that speak norwegian with those who wish to practice and do so over dinner.',

    'Registrer deg nedenfor dersom du vil komme på middag.': 'Register in the form beneath if you want to be invited for dinner',

    'Registrer deg nedenfor dersom du vil invitere noen på middag.': 'Register in the form beneath if you would like to invite someone for dinner',

    'Gjestene er noen som har nylig kommet til Norge, og de fleste melder seg på etter at Kom inn har blitt presentert på Voksenopplæringene i Oslo. Vertene er noen som snakker norsk flytende. Alle som deltar har meldt seg på via denne nettsiden. Våre frivillige prøver å sette sammen en hyggeligst mulig middag. Når vi finner en match setter vi dere i kontakt, slik at dere selv kan avtale detaljene.': 'The guests are someone who are new to Norway and most of them register after hearing about Kom inn at the "Voksenopplæring" in Oslo. The hosts are someone who speaks fluent Norwegian. All have registered through this site. Our volunteers try to find the best matches possible. When we find a match we will connect you, so you can arrange the details of the dinner yourselves.',
    'Har du andre spørsmål?': 'Do you have any other questions?',
    'Det er ingen forpliktelser ved å melde seg på utover å møtes til én middag. De fleste gjester inviterer likevel tilbake og noen har kontakt i lang tid. Det er helt opp til dere, deltakelse er helt frivillig og på eget ansvar.': 'The only obligation by registrering is to meet for one dinner. Most guests do invite back, and keep in touch later. However, it is up to you to decide. Participation in Kom inn is completely voluntary and at your own risk.',
    'For deg som bor utenfor Oslo : Kom inn er enda ikke etablert over hele landet. Vi håper å få til dette i løpet av ikke så lang tid. Vi tar kontakt med deg når vi har gjester i ditt området!': 'If you live outside of Oslo: Kom inn is only established in Oslo so far. We hope to grow our coverage soon. We will contact you when we have guests in your area!',
    'Du kan lese mer på': 'You can read more on',
    'Vi vil prøve å finne noen du kan invitere på middag så fort så mulig. Når vi har funnet passende gjester - hører du fra oss!': 'We will try to find someone for you to invite as quickly as possible. You will hear from us when we have found some guests for you!',
    'Noen ganger går det noen dager, andre ganger bruker vi flere uker. Dette kan variere veldig. Vi forsøker så godt vi kan å finne rett match så opplevelsen for begge parter skal bli best mulig. Hvis du synes det går for lang tid er det lov å sende oss en mail.': 'Sometimes this is done in days, other times we need several weeks. It can vary greatly. We try to find the right match that ensures both parties has the best possible experience. If you think it is taking too long, you can send us an email.',
    'Hilsen oss i Kom inn.': 'From us in Kom inn',
    'Hvor mange blir med på middag i tillegg til deg': 'How many guests are you bringing with you in addition to yourself',
    'Kan du fortelle litt mer om deg selv': 'Can you tell us a bit more about yourself',
    'Er det noe annet vi trenger å vite om deg/dere': 'Is there anything else we should know about you',
    'Send inn': 'Submit',
    'Hvordan kan vi kontakte deg': "How can we contact you",
    'Hvor bor du': 'Where do you live',
    'Annet': 'Anything else',
    'Hvem tar du med deg? Vet vi mer er sjansen for at vi finner en god match større.': 'Who are you bringing? The more we know, the better chance for a good match.',
    'Del på Facebook': 'Share on Facebook',
    'Takk': 'Thanks',
    'Hva skjer nå?': 'What happens now?',
    'Vi vil nå matche deg med noen som ønsker å invitere deg, vanligvis innen to uker.': 'We\'ll now match you with someone who wants to invite you, usually within two weeks.',
    'Du vil da motta en invitasjon via SMS fra verten.': 'You will receive an invitation via SMS from the host.',
    'Sammen blir dere enige om når du kommer til huset til middag.': 'Together you decide when to meet for dinner.',
    'Les mer på': 'Read more at',
    'eller send en epost til': 'Or send an email to',
    'For flere detaljer': 'For more details',
    'Ha en fortsatt fin dag!': 'Have a nice day!',
    'Vennligst skriv inn en gyldig alder': 'Please enter a valid age',
    'Vennligst oppgi en gyldig epostadresse': 'Please enter a valid email address',
    'Vennligst oppgi et gyldig telefonnummer': 'Please enter a valid phone number',
    'Gyldig kode må ligge mellom 0001 og 9999': 'Valid code must lie between 0001 and 9999',
    'Del på Facebook': 'Share on Facebook',
    'Takk skal du ha': 'Thank you',
    'vær så snill å fikse uthevede feil': 'Please fix highlighted errors',
    'vennligst velg kjønn': 'Please select gender',
    'Dette gjør vi med det du registrerer: En av våre frivillige prøver å finne en middagsgjest eller middagsvert som passer for deg, og gir gjestens informasjon videre til verten, slik at dere kan kan prate sammen og avtale en middag. Etter en stund vil du få e-post fra oss hvor vi spør deg om du fortsatt vil være registrert. Vi sletter informasjonen om deg automatisk etter 90 dager, hvis du ikke sier ja til å fortsatt være registrert. Ønsker du å slette opplysningene dine før, kan du alltids sende oss en e-post på': 'How we handle your information: One of our volunteers looks at your information and finds a suitable dinner guest or host. We send the guest’s information to the host, so that you can communicate. You will receive emails from us asking you if you still want to be registered. If you don’t take any action, your information will be deleted automatically after a maximum of 90 days. If you want to delete your information earlier, send us an email on'
}
