module.exports = {
    'Mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk': 'People that speak Norwegian invite people who want to learn Norwegian over for dinner',
    'Hvis du vil komme på middag, eller invitere noen på middag registrerer du deg nedenfor. Vi matcher dere basert på hvem dere er og hvor dere bor og setter dere i kontakt for å avtale tidspunkt.': 'If you want to join a dinner or invite someone for a dinner register below. We will match you based on who you are and where you live. We will then set you in touch with each other',
    'Du finner mer informasjon på': 'More information are available here',

    'Hva vil du': 'What do you to do',
    'Komme til noen på middagsbesøk': 'Join someone for dinner',
    'Invitere noen på middagsbesøk': 'Invite someone to dinner',
    'Hva er navnet ditt': 'What\'s your name',
    'Hva er e-postadressen din': 'What\'s your email address',
    'Hva er telefonnummeret ditt': 'What\'s your phone number',
    'Er det noe mat du ikke spiser': 'Is there any food you don\'t eat',
    'Er du': 'Are you',
    'Kjønn': 'Gender',
    'Mann': 'Male',
    'Kvinne': 'Female',
    'Menn': 'Males',
    'Kvinner': 'Females',
    'Barn': 'Children',
    'Alder': 'Age',
    'År': 'Years',
    'Antall barn': 'Children',
    'Antall voksne menn': 'Male adults',
    'Antall voksne kvinner': 'Female adults',
    'Hvor er du fra': 'Where are you from',
    'Hvor mange blir med på middag': 'How many people are you bringing',
    'Er det noe mat du/dere ikke spiser': 'Is there any food you don\'t eat',
    'Adresse': 'Address',
    'Dette er ikke et gyldig navn':'This is not a valid name',
    'Dette er ikke en gyldig alder':'This is not a valid age',
    'Dette er ikke et gyldig sted':'This is not a valid location',
    'Dette er ikke et gyldig nummer':'This is not a valid number',
    'Dette er ikke en gyldig epost':'This is not a valid email',
    'Dette er ikke et gyldig telefonnummer':'This is not a valid phone number',
    'Dette er ikke en gyldig adresse':'This is not a valid address',
    'Dette er ikke en gyldig postnummer':'This is not a valid zipcode',
    'Postnummer': 'Zip code',
    'Hvem er du': "Who are you",
    'Vil du heller invitere noen på middag,': 'Would you rather invite someone,',
    'gå til skjema for vert.': 'go to the form for hosts.',
    'Vil du heller bli invitert på middag,': 'Would you rather be invited,',
    'gå til skjema for gjest.': 'go to the form for guests.',
    'Jeg vil komme på middag!': 'I would like to be invited to a dinner!',
    'Jeg vil invitere noen på middag!': 'I would like to invite someone over for dinner!',
    'Vil du øve på å snakke norsk? Ideen bak Kom inn er at mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk.':
        'Do you wish to practise speaking Norwegian? The concept behind Kom inn is to match people that speak norwegian with those who wish to practice and do so over dinner.',
    'Vil du hjelpe noen å lære norsk? Ideen bak Kom inn er at mennesker som snakker norsk inviterer noen som lærer seg norsk på middagsbesøk.':
        'Do you wish to help someone learn Norwegian? The concept behind Kom inn is to match people that speak norwegian with those who wish to practice and do so over dinner.',
    'Registrer deg nedenfor dersom du vil komme på middag. For å koble dere trenger vi å vite litt om hvem dere er og hvor dere bor. Når vi finner en match ber vi verten ta kontakt for å avtale tidspunkt.':
        'Register below if you wish to be invited to a Norwegian dinner. To find a match we need to know a little bit about you and where you live. When we find a match we, a host will contact you with an invitation.',
    'Registrer deg nedenfor dersom du vil invitere noen på middag. For å koble dere trenger vi å vite litt om hvem dere er og hvor dere bor. Når vi finner en match setter vi dere i kontakt for å avtale tidspunkt.':
        'Register below if you wish to invite someone over for dinner. To find a match we need to know a little bit about you and where you live. When we find a match we will ask you to contact the guest with an invitation.',
    'Hvor mange blir med på middag i tillegg til deg': 'How many guests are you bringing with you in addition to yourself',
    'Kan du fortelle litt mer om deg selv': 'Can you tell us a bit more about yourself',
    'Er det noe annet vi trenger å vite om deg/dere': 'Is there anything else we should know about you',
    'Send inn': 'Submit',
    'Hvordan kan vi kontakte deg': "How can we contact you",
    'Hvor bor du': 'Where do you live',
    'Annet': 'Anything else',
    'Hvem tar du med deg? Vet vi mer er sjansen for at vi finner en god match større. Eksempelvis alder på barna.': 'Who are you bringing? The more we know, the better chance for a good match. For example, what is the age of your kids.',
    'Takk skal du ha': 'Thank you',
    'vær så snill å fikse uthevede feil': 'Please fix highlighted errors',
    'vennligst velg kjønn': 'Please select gender',
    'Del på Facebook': 'Share on Facebook'
}
