---
- hosts:
  - dev
  - pro
  become: true
  tasks:
  - name: setup cronjobs
    template: src=../templates/kom-inn-cron.tpl dest=/etc/cron.d/kom-inn owner=root
    notify: restart cron
  handlers:
  - name: restart cron
    service: name=cron state=restarted
